# fly.toml app configuration file generated for shorter-link on 2024-01-22T13:58:10+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shorter-link"
primary_region = "sin"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "storage_dir"
  destination = "/data"